name: Run Postman Tests

on: [push, pull_request]

jobs:
  postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Newman & HTML Reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run 8.API_Chaining.json -e postman_environment.json 

      
